"""Concrete S4 scenario generated by tools/make_scenario.py -- do not edit by hand.

Same scenario as scenarios/s4_scenic.scenic (and s4_v1.xml), but with the randomized
quantities baked in: ego  vehicle.tesla.model3             carla=(  405.60,   -87.00)
  npc  vehicle.jeep.wrangler_rubicon    carla=(  405.43,   -66.75) lane=own   gap=20.3 m
  npc  vehicle.audi.tt                  carla=(  402.08,   -81.70) lane=left  gap=5.3 m
  npc  vehicle.audi.a2                  carla=(  401.98,   -71.71) lane=left  gap=15.3 m
  npc  vehicle.audi.tt                  carla=(  409.05,   -78.50) lane=right gap=8.5 m

All values were drawn by the generator, the script itself contains no random choice,
so every run of it starts from exactly the same scene.  Run it with

    runner/run_scenic_s4.py --scenic scenarios/generated_v2/s4_v7.scenic --config-json <dir>/ind_<i>.json

(weather: WetNoon)
"""

param map = localPath('../Town04.xodr')
param carla_map = 'Town04'
param address = '127.0.0.1'
param port = 2000
param timeout = 120
param render = 0
param timestep = 0.025
param weather = 'WetNoon'

model scenic.simulators.carla.model
from s4_bridge import *
from s4_behaviors import *   # noqa: F403  (behavior definitions)

ego = Car at Vector(405.6, 87.0),
    with blueprint 'vehicle.tesla.model3',
    with color Color(r=0.4521759268770321, g=0.02786575824017179, b=0.8940120779908302),
    with rolename 'ego_vehicle',
    with behavior S4EgoBehavior()

npc1 = Car at Vector(405.430940980598, 66.74668122195267),
    with blueprint 'vehicle.jeep.wrangler_rubicon',
    with color Color(r=0.06336883785760694, g=0.3256136373618832, b=0.973360251676687),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc2 = Car at Vector(402.07619627578146, 81.70211820996599),
    with blueprint 'vehicle.audi.tt',
    with color Color(r=0.6061376818430533, g=0.19940320918508614, b=0.2771855402912631),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc3 = Car at Vector(401.98262451811684, 71.7104573235436),
    with blueprint 'vehicle.audi.a2',
    with color Color(r=0.5081561545527385, g=0.8073621427866542, b=0.5077518592886711),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc4 = Car at Vector(409.0513264992553, 78.4966149659157),
    with blueprint 'vehicle.audi.tt',
    with color Color(r=0.24765579923404657, g=0.5232096528748831, b=0.8759766440255983),
    with behavior NpcFollowLaneBehavior(12.708333333333334)


# the run ends once the ego has completed its lane change
terminate when lane_change_done(ego)
