"""Concrete S4 scenario generated by tools/make_scenario.py -- do not edit by hand.

Same scenario as scenarios/s4_scenic.scenic (and s4_v4.xml), but with the randomized
quantities baked in: ego  vehicle.tesla.model3             carla=(  405.60,   -87.00)
  npc  vehicle.jeep.wrangler_rubicon    carla=(  409.10,   -70.90) lane=right gap=16.1 m
  npc  vehicle.audi.tt                  carla=(  402.10,   -82.60) lane=left  gap=4.4 m
  npc  vehicle.audi.a2                  carla=(  405.60,   -76.80) lane=own   gap=10.2 m
  npc  vehicle.audi.tt                  carla=(  402.10,   -75.60) lane=left  gap=11.4 m

All values were drawn by the generator, the script itself contains no random choice,
so every run of it starts from exactly the same scene.  Run it with

    runner/run_scenic_s4.py --scenic scenarios/generated_v2/s4_v4.scenic --config-json <dir>/ind_<i>.json

(weather: ClearSunset)
The NPC start positions were aligned to scripts_with_setting/openscenario/s4_v4.xml;
the generator's randomized lane/gap draw was replaced.
"""

param map = localPath('../Town04.xodr')
param carla_map = 'Town04'
param address = '127.0.0.1'
param port = 2000
param timeout = 120
param render = 0
param timestep = 0.025
param weather = 'ClearSunset'

model scenic.simulators.carla.model
from s4_bridge import *
from s4_behaviors import *   # noqa: F403  (behavior definitions)

ego = Car at Vector(405.6, 87.0),
    with blueprint 'vehicle.tesla.model3',
    with color Color(r=0.47913068291095273, g=0.8863261770099526, b=0.22217205627163472),
    with rolename 'ego_vehicle',
    with behavior S4EgoBehavior()

npc1 = Car at Vector(409.1, 70.9),
    with blueprint 'vehicle.jeep.wrangler_rubicon',
    with color Color(r=0.786676942044965, g=0.6602638684426625, b=0.8527746567712856),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc2 = Car at Vector(402.1, 82.6),
    with blueprint 'vehicle.audi.tt',
    with color Color(r=0.6877593279340223, g=0.8810384094643154, b=0.23743366373236963),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc3 = Car at Vector(405.6, 76.8),
    with blueprint 'vehicle.audi.a2',
    with color Color(r=0.48983572947673115, g=0.22111948810276805, b=0.3676172139523074),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc4 = Car at Vector(402.1, 75.6),
    with blueprint 'vehicle.audi.tt',
    with color Color(r=0.7456730926529873, g=0.5372266220062727, b=0.529760777923831),
    with behavior NpcFollowLaneBehavior(12.708333333333334)


# the run ends once the ego has completed its lane change
terminate when lane_change_done(ego)
