"""Concrete S4 scenario generated by tools/make_scenario.py -- do not edit by hand.

Same scenario as scenarios/s4_scenic.scenic (and s4_v7.xml), but with the randomized
quantities baked in: ego  vehicle.tesla.model3             carla=(  405.60,   -87.00)
  npc  vehicle.jeep.wrangler_rubicon    carla=(  409.10,   -75.90) lane=right gap=11.1 m
  npc  vehicle.audi.tt                  carla=(  402.10,   -79.20) lane=left  gap=7.8 m
  npc  vehicle.audi.a2                  carla=(  409.10,   -67.90) lane=right gap=19.1 m
  npc  vehicle.audi.tt                  carla=(  402.10,   -72.20) lane=left  gap=14.8 m

All values were drawn by the generator, the script itself contains no random choice,
so every run of it starts from exactly the same scene.  Run it with

    runner/run_scenic_s4.py --scenic scenarios/generated_v2/s4_v7.scenic --config-json <dir>/ind_<i>.json

(weather: WetNoon)
The NPC start positions were aligned to scripts_with_setting/openscenario/s4_v7.xml;
the generator's randomized lane/gap draw was replaced.
"""

param map = localPath('../Town04.xodr')
param carla_map = 'Town04'
param address = '127.0.0.1'
param port = 2000
param timeout = 120
param render = 0
param timestep = 0.025
param weather = 'WetNoon'

model scenic.simulators.carla.model
from s4_bridge import *
from s4_behaviors import *   # noqa: F403  (behavior definitions)

ego = Car at Vector(405.6, 87.0),
    with blueprint 'vehicle.tesla.model3',
    with color Color(r=0.4521759268770321, g=0.02786575824017179, b=0.8940120779908302),
    with rolename 'ego_vehicle',
    with behavior S4EgoBehavior()

npc1 = Car at Vector(409.1, 75.9),
    with blueprint 'vehicle.jeep.wrangler_rubicon',
    with color Color(r=0.06336883785760694, g=0.3256136373618832, b=0.973360251676687),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc2 = Car at Vector(402.1, 79.2),
    with blueprint 'vehicle.audi.tt',
    with color Color(r=0.6061376818430533, g=0.19940320918508614, b=0.2771855402912631),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc3 = Car at Vector(409.1, 67.9),
    with blueprint 'vehicle.audi.a2',
    with color Color(r=0.5081561545527385, g=0.8073621427866542, b=0.5077518592886711),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc4 = Car at Vector(402.1, 72.2),
    with blueprint 'vehicle.audi.tt',
    with color Color(r=0.24765579923404657, g=0.5232096528748831, b=0.8759766440255983),
    with behavior NpcFollowLaneBehavior(12.708333333333334)


# the run ends once the ego has completed its lane change
terminate when lane_change_done(ego)
