"""Concrete S4 scenario generated by tools/make_scenario.py -- do not edit by hand.

Same scenario as scenarios/s4_scenic.scenic (and s4_v1.xml), but with the randomized
quantities baked in: ego  vehicle.tesla.model3             carla=(  405.60,   -87.00)
  npc  vehicle.jeep.wrangler_rubicon    carla=(  409.07,   -80.90) lane=right gap=6.1 m
  npc  vehicle.audi.tt                  carla=(  402.05,   -78.83) lane=left  gap=8.2 m
  npc  vehicle.audi.a2                  carla=(  401.94,   -67.84) lane=left  gap=19.2 m
  npc  vehicle.audi.tt                  carla=(  408.92,   -65.25) lane=right gap=21.7 m

All values were drawn by the generator, the script itself contains no random choice,
so every run of it starts from exactly the same scene.  Run it with

    runner/run_scenic_s4.py --scenic scenarios/generated_v2/s4_v9.scenic --config-json <dir>/ind_<i>.json

(weather: MidRainyNoon)
"""

param map = localPath('../Town04.xodr')
param carla_map = 'Town04'
param address = '127.0.0.1'
param port = 2000
param timeout = 120
param render = 0
param timestep = 0.025
param weather = 'MidRainyNoon'

model scenic.simulators.carla.model
from s4_bridge import *
from s4_behaviors import *   # noqa: F403  (behavior definitions)

ego = Car at Vector(405.6, 87.0),
    with blueprint 'vehicle.tesla.model3',
    with color Color(r=0.19767034720855536, g=0.8521963820088893, b=0.33021669841000845),
    with rolename 'ego_vehicle',
    with behavior S4EgoBehavior()

npc1 = Car at Vector(409.0697634251452, 80.90227736354598),
    with blueprint 'vehicle.jeep.wrangler_rubicon',
    with color Color(r=0.8924752182029455, g=0.13318339392371048, b=0.9176574648727837),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc2 = Car at Vector(402.0536643431615, 78.82848103039585),
    with blueprint 'vehicle.audi.tt',
    with color Color(r=0.5008033892872673, g=0.5729781426246586, b=0.5375876420805329),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc3 = Car at Vector(401.9421868598129, 67.84004432746958),
    with blueprint 'vehicle.audi.a2',
    with color Color(r=0.19817545577963758, g=0.06882018892567465, b=0.1921644928955848),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc4 = Car at Vector(408.9154613670506, 65.24809434558813),
    with blueprint 'vehicle.audi.tt',
    with color Color(r=0.7648977048204675, g=0.700847659854592, b=0.14535719284828885),
    with behavior NpcFollowLaneBehavior(12.708333333333334)


# the run ends once the ego has completed its lane change
terminate when lane_change_done(ego)
