"""Concrete S4 scenario generated by tools/make_scenario.py -- do not edit by hand.

Same scenario as scenarios/s4_scenic.scenic (and s4_v2.xml), but with the randomized
quantities baked in: ego  vehicle.tesla.model3             carla=(  405.60,   -87.00)
  npc  vehicle.jeep.wrangler_rubicon    carla=(  405.60,   -69.40) lane=own   gap=17.6 m
  npc  vehicle.audi.tt                  carla=(  405.60,   -81.00) lane=own   gap=6.0 m
  npc  vehicle.audi.a2                  carla=(  409.10,   -71.30) lane=right gap=15.7 m

All values were drawn by the generator, the script itself contains no random choice,
so every run of it starts from exactly the same scene.  Run it with

    runner/run_scenic_s4.py --scenic scenarios/generated_v2/s4_v2.scenic --config-json <dir>/ind_<i>.json

(weather: ClearSunset)
The NPC start positions were aligned to scripts_with_setting/openscenario/s4_v2.xml;
the generator's randomized lane/gap draw was replaced.
"""

param map = localPath('../Town04.xodr')
param carla_map = 'Town04'
param address = '127.0.0.1'
param port = 2000
param timeout = 120
param render = 0
param timestep = 0.025
param weather = 'ClearSunset'

model scenic.simulators.carla.model
from s4_bridge import *
from s4_behaviors import *   # noqa: F403  (behavior definitions)

ego = Car at Vector(405.6, 87.0),
    with blueprint 'vehicle.tesla.model3',
    with color Color(r=0.23612340711506208, g=0.023858079140782196, b=0.32514292876116),
    with rolename 'ego_vehicle',
    with behavior S4EgoBehavior()

npc1 = Car at Vector(405.6, 69.4),
    with blueprint 'vehicle.jeep.wrangler_rubicon',
    with color Color(r=0.13669739298646666, g=0.5102238458372012, b=0.998683568192552),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc2 = Car at Vector(405.6, 81.0),
    with blueprint 'vehicle.audi.tt',
    with color Color(r=0.6744796973458701, g=0.18184349682314438, b=0.8935715365829885),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc3 = Car at Vector(409.1, 71.3),
    with blueprint 'vehicle.audi.a2',
    with color Color(r=0.7967599214216395, g=0.7344016918939777, b=0.906593649897561),
    with behavior NpcFollowLaneBehavior(12.708333333333334)


# the run ends once the ego has completed its lane change
terminate when lane_change_done(ego)
