"""Concrete S4 scenario generated by tools/make_scenario.py -- do not edit by hand.

Same scenario as scenarios/s4_scenic.scenic (and s4_v1.xml), but with the randomized
quantities baked in: ego  vehicle.tesla.model3             carla=(  405.60,   -87.00)
  npc  vehicle.jeep.wrangler_rubicon    carla=(  401.91,   -65.16) lane=left  gap=21.9 m
  npc  vehicle.audi.tt                  carla=(  408.89,   -62.60) lane=right gap=24.4 m
  npc  vehicle.audi.a2                  carla=(  409.07,   -81.32) lane=right gap=5.6 m
  npc  vehicle.audi.tt                  carla=(  402.05,   -78.66) lane=left  gap=8.4 m

All values were drawn by the generator, the script itself contains no random choice,
so every run of it starts from exactly the same scene.  Run it with

    runner/run_scenic_s4.py --scenic scenarios/generated_v2/s4_v3.scenic --config-json <dir>/ind_<i>.json

(weather: ClearSunset)
"""

param map = localPath('../Town04.xodr')
param carla_map = 'Town04'
param address = '127.0.0.1'
param port = 2000
param timeout = 120
param render = 0
param timestep = 0.025
param weather = 'ClearSunset'

model scenic.simulators.carla.model
from s4_bridge import *
from s4_behaviors import *   # noqa: F403  (behavior definitions)

ego = Car at Vector(405.6, 87.0),
    with blueprint 'vehicle.tesla.model3',
    with color Color(r=0.8965671649840485, g=0.899674836023798, b=0.5769534040194515),
    with rolename 'ego_vehicle',
    with behavior S4EgoBehavior()

npc1 = Car at Vector(401.91420428230305, 65.16174552876126),
    with blueprint 'vehicle.jeep.wrangler_rubicon',
    with color Color(r=0.013144496687112928, g=0.7452982673109616, b=0.17182159053673707),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc2 = Car at Vector(408.88782699476275, 62.60312334262781),
    with blueprint 'vehicle.audi.tt',
    with color Color(r=0.29988806872849316, g=0.6628961043048281, b=0.5249641354158249),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc3 = Car at Vector(409.07314364152967, 81.32348670332536),
    with blueprint 'vehicle.audi.a2',
    with color Color(r=0.41375044772957725, g=0.9390424632510898, b=0.6121639096259125),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc4 = Car at Vector(402.0523491375194, 78.65687224545105),
    with blueprint 'vehicle.audi.tt',
    with color Color(r=0.34135265741799514, g=0.25247484424703104, b=0.861664716459667),
    with behavior NpcFollowLaneBehavior(12.708333333333334)


# the run ends once the ego has completed its lane change
terminate when lane_change_done(ego)
