"""Concrete S4 scenario generated by tools/make_scenario.py -- do not edit by hand.

Same scenario as scenarios/s4_scenic.scenic (and s4_v1.xml), but with the randomized
quantities baked in: ego  vehicle.tesla.model3             carla=(  405.60,   -87.00)
  npc  vehicle.jeep.wrangler_rubicon    carla=(  409.01,   -74.70) lane=right gap=12.3 m
  npc  vehicle.audi.tt                  carla=(  402.06,   -79.90) lane=left  gap=7.1 m
  npc  vehicle.audi.a2                  carla=(  409.08,   -81.57) lane=right gap=5.4 m
  npc  vehicle.audi.tt                  carla=(  405.40,   -64.20) lane=own   gap=22.8 m

All values were drawn by the generator, the script itself contains no random choice,
so every run of it starts from exactly the same scene.  Run it with

    runner/run_scenic_s4.py --scenic scenarios/generated_v2/s4_v1.scenic --config-json <dir>/ind_<i>.json

(weather: ClearSunset)
"""

param map = localPath('../Town04.xodr')
param carla_map = 'Town04'
param address = '127.0.0.1'
param port = 2000
param timeout = 120
param render = 0
param timestep = 0.025
param weather = 'ClearSunset'

model scenic.simulators.carla.model
from s4_bridge import *
from s4_behaviors import *   # noqa: F403  (behavior definitions)

ego = Car at Vector(405.6, 87.0),
    with blueprint 'vehicle.tesla.model3',
    with color Color(r=0.8170396683778869, g=0.020818108509287336, b=0.017864520827795327),
    with rolename 'ego_vehicle',
    with behavior S4EgoBehavior()

npc1 = Car at Vector(409.01425004060326, 74.70346298017685),
    with blueprint 'vehicle.jeep.wrangler_rubicon',
    with color Color(r=0.146461740399346, g=0.7188354727617898, b=0.16022759262970465),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc2 = Car at Vector(402.06187427590595, 79.89971775392354),
    with blueprint 'vehicle.audi.tt',
    with color Color(r=0.7046056278520025, g=0.6781757952769475, b=0.5447021635789044),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc3 = Car at Vector(409.0752944375092, 81.57063920926043),
    with blueprint 'vehicle.audi.a2',
    with color Color(r=0.22059974802267657, g=0.9755945178178834, b=0.797810857706151),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc4 = Car at Vector(405.4043837565778, 64.20480740188366),
    with blueprint 'vehicle.audi.tt',
    with color Color(r=0.516599516949393, g=0.22319578024667075, b=0.6485064180992564),
    with behavior NpcFollowLaneBehavior(12.708333333333334)


# the run ends once the ego has completed its lane change
terminate when lane_change_done(ego)
