"""Concrete S4 scenario generated by tools/make_scenario.py -- do not edit by hand.

Same scenario as scenarios/s4_scenic.scenic (and s4_v10.xml), but with the randomized
quantities baked in: ego  vehicle.tesla.model3             carla=(  405.60,   -87.00)
  npc  vehicle.jeep.wrangler_rubicon    carla=(  409.10,   -74.60) lane=right gap=12.4 m
  npc  vehicle.audi.tt                  carla=(  402.10,   -83.20) lane=left  gap=3.8 m
  npc  vehicle.audi.a2                  carla=(  402.10,   -72.50) lane=left  gap=14.5 m
  npc  vehicle.audi.tt                  carla=(  409.10,   -67.60) lane=right gap=19.4 m

All values were drawn by the generator, the script itself contains no random choice,
so every run of it starts from exactly the same scene.  Run it with

    runner/run_scenic_s4.py --scenic scenarios/generated_v2/s4_v10.scenic --config-json <dir>/ind_<i>.json

(weather: ClearSunset)
The NPC start positions were aligned to scripts_with_setting/openscenario/s4_v10.xml;
the generator's randomized lane/gap draw was replaced.
"""

param map = localPath('../Town04.xodr')
param carla_map = 'Town04'
param address = '127.0.0.1'
param port = 2000
param timeout = 120
param render = 0
param timestep = 0.025
param weather = 'ClearSunset'

model scenic.simulators.carla.model
from s4_bridge import *
from s4_behaviors import *   # noqa: F403  (behavior definitions)

ego = Car at Vector(405.6, 87.0),
    with blueprint 'vehicle.tesla.model3',
    with color Color(r=0.7827646033997006, g=0.007747562301112398, b=0.4238781527412905),
    with rolename 'ego_vehicle',
    with behavior S4EgoBehavior()

npc1 = Car at Vector(409.1, 74.6),
    with blueprint 'vehicle.jeep.wrangler_rubicon',
    with color Color(r=0.40846320893562404, g=0.3818426346133459, b=0.8121144969184942),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc2 = Car at Vector(402.1, 83.2),
    with blueprint 'vehicle.audi.tt',
    with color Color(r=0.1997407381994476, g=0.7722759278380728, b=0.7971193350033632),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc3 = Car at Vector(402.1, 72.5),
    with blueprint 'vehicle.audi.a2',
    with color Color(r=0.8238868121448889, g=0.3480044920347488, b=0.360222134417845),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc4 = Car at Vector(409.1, 67.6),
    with blueprint 'vehicle.audi.tt',
    with color Color(r=0.4241711553886496, g=0.1936200755003209, b=0.7494461333936795),
    with behavior NpcFollowLaneBehavior(12.708333333333334)


# the run ends once the ego has completed its lane change
terminate when lane_change_done(ego)
