"""Concrete S4 scenario generated by tools/make_scenario.py -- do not edit by hand.

Same scenario as scenarios/s4_scenic.scenic (and s4_v1.xml), but with the randomized
quantities baked in: ego  vehicle.tesla.model3             carla=(  405.60,   -87.00)
  npc  vehicle.jeep.wrangler_rubicon    carla=(  402.06,   -80.03) lane=left  gap=7.0 m
  npc  vehicle.audi.tt                  carla=(  401.91,   -64.95) lane=left  gap=22.1 m
  npc  vehicle.audi.a2                  carla=(  409.02,   -75.40) lane=right gap=11.6 m
  npc  vehicle.audi.tt                  carla=(  408.94,   -67.20) lane=right gap=19.8 m

All values were drawn by the generator, the script itself contains no random choice,
so every run of it starts from exactly the same scene.  Run it with

    runner/run_scenic_s4.py --scenic scenarios/generated_v2/s4_v5.scenic --config-json <dir>/ind_<i>.json

(weather: ClearSunset)
"""

param map = localPath('../Town04.xodr')
param carla_map = 'Town04'
param address = '127.0.0.1'
param port = 2000
param timeout = 120
param render = 0
param timestep = 0.025
param weather = 'ClearSunset'

model scenic.simulators.carla.model
from s4_bridge import *
from s4_behaviors import *   # noqa: F403  (behavior definitions)

ego = Car at Vector(405.6, 87.0),
    with blueprint 'vehicle.tesla.model3',
    with color Color(r=0.44483568613752145, g=0.13224085421692466, b=0.9723372896865363),
    with rolename 'ego_vehicle',
    with behavior S4EgoBehavior()

npc1 = Car at Vector(402.06287976083064, 80.03091400239161),
    with blueprint 'vehicle.jeep.wrangler_rubicon',
    with color Color(r=0.00531313724410809, g=0.7735937030276743, b=0.9601271002174996),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc2 = Car at Vector(401.91202584924616, 64.95324098205413),
    with blueprint 'vehicle.audi.tt',
    with color Color(r=0.16585644239491049, g=0.16648447729129467, b=0.3136513677349536),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc3 = Car at Vector(409.0214857523681, 75.3960152699303),
    with blueprint 'vehicle.audi.a2',
    with color Color(r=0.19888932659643488, g=0.8761189332442766, b=0.6257301956771277),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc4 = Car at Vector(408.93587267876825, 67.20172394364647),
    with blueprint 'vehicle.audi.tt',
    with color Color(r=0.1816686685456037, g=0.9685567743379022, b=0.19687904392603262),
    with behavior NpcFollowLaneBehavior(12.708333333333334)


# the run ends once the ego has completed its lane change
terminate when lane_change_done(ego)
