"""Concrete S4 scenario generated by tools/make_scenario.py -- do not edit by hand.

Same scenario as scenarios/s4_scenic.scenic (and s4_v6.xml), but with the randomized
quantities baked in: ego  vehicle.tesla.model3             carla=(  405.60,   -87.00)
  npc  vehicle.jeep.wrangler_rubicon    carla=(  402.10,   -74.40) lane=left  gap=12.6 m
  npc  vehicle.audi.tt                  carla=(  409.10,   -80.90) lane=right gap=6.1 m
  npc  vehicle.audi.a2                  carla=(  402.10,   -67.40) lane=left  gap=19.6 m
  npc  vehicle.audi.tt                  carla=(  405.60,   -81.00) lane=own   gap=6.0 m

All values were drawn by the generator, the script itself contains no random choice,
so every run of it starts from exactly the same scene.  Run it with

    runner/run_scenic_s4.py --scenic scenarios/generated_v2/s4_v6.scenic --config-json <dir>/ind_<i>.json

(weather: CloudyNoon)
The NPC start positions were aligned to scripts_with_setting/openscenario/s4_v6.xml;
the generator's randomized lane/gap draw was replaced.
"""

param map = localPath('../Town04.xodr')
param carla_map = 'Town04'
param address = '127.0.0.1'
param port = 2000
param timeout = 120
param render = 0
param timestep = 0.025
param weather = 'CloudyNoon'

model scenic.simulators.carla.model
from s4_bridge import *
from s4_behaviors import *   # noqa: F403  (behavior definitions)

ego = Car at Vector(405.6, 87.0),
    with blueprint 'vehicle.tesla.model3',
    with color Color(r=0.7152161964072316, g=0.1258518801564804, b=0.6908562121032468),
    with rolename 'ego_vehicle',
    with behavior S4EgoBehavior()

npc1 = Car at Vector(402.1, 74.4),
    with blueprint 'vehicle.jeep.wrangler_rubicon',
    with color Color(r=0.7572910436727015, g=0.9934252369428691, b=0.5610139859643821),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc2 = Car at Vector(409.1, 80.9),
    with blueprint 'vehicle.audi.tt',
    with color Color(r=0.004764450985328517, g=0.805084948010112, b=0.3866854622076915),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc3 = Car at Vector(402.1, 67.4),
    with blueprint 'vehicle.audi.a2',
    with color Color(r=0.7602381730471784, g=0.8549406333348232, b=0.5262980270456036),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc4 = Car at Vector(405.6, 81.0),
    with blueprint 'vehicle.audi.tt',
    with color Color(r=0.009674417954021686, g=0.8448701649719516, b=0.5307905417014571),
    with behavior NpcFollowLaneBehavior(12.708333333333334)


# the run ends once the ego has completed its lane change
terminate when lane_change_done(ego)
