"""Concrete S4 scenario generated by tools/make_scenario.py -- do not edit by hand.

Same scenario as scenarios/s4_scenic.scenic (and s4_v1.xml), but with the randomized
quantities baked in: ego  vehicle.tesla.model3             carla=(  405.60,   -87.00)
  npc  vehicle.jeep.wrangler_rubicon    carla=(  402.05,   -78.13) lane=left  gap=8.9 m
  npc  vehicle.audi.tt                  carla=(  401.88,   -62.14) lane=left  gap=24.9 m
  npc  vehicle.audi.a2                  carla=(  408.97,   -70.06) lane=right gap=16.9 m
  npc  vehicle.audi.tt                  carla=(  409.05,   -78.58) lane=right gap=8.4 m

All values were drawn by the generator, the script itself contains no random choice,
so every run of it starts from exactly the same scene.  Run it with

    runner/run_scenic_s4.py --scenic scenarios/generated_v2/s4_v8.scenic --config-json <dir>/ind_<i>.json

(weather: CloudyNoon)
"""

param map = localPath('../Town04.xodr')
param carla_map = 'Town04'
param address = '127.0.0.1'
param port = 2000
param timeout = 120
param render = 0
param timestep = 0.025
param weather = 'CloudyNoon'

model scenic.simulators.carla.model
from s4_bridge import *
from s4_behaviors import *   # noqa: F403  (behavior definitions)

ego = Car at Vector(405.6, 87.0),
    with blueprint 'vehicle.tesla.model3',
    with color Color(r=0.45793514884933073, g=0.23423075536841942, b=0.8109302639707848),
    with rolename 'ego_vehicle',
    with behavior S4EgoBehavior()

npc1 = Car at Vector(402.04829052487713, 78.12730214490844),
    with blueprint 'vehicle.jeep.wrangler_rubicon',
    with color Color(r=0.5252458365986113, g=0.19538320875123472, b=0.4966484142897003),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc2 = Car at Vector(401.88264962474346, 62.14155193131217),
    with blueprint 'vehicle.audi.tt',
    with color Color(r=0.1057476311433152, g=0.11162630757645176, b=0.0842238713405401),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc3 = Car at Vector(408.96569502765146, 70.05611293480845),
    with blueprint 'vehicle.audi.a2',
    with color Color(r=0.17070770844996075, g=0.5667441710314373, b=0.4275750958953133),
    with behavior NpcFollowLaneBehavior(12.708333333333334)

npc4 = Car at Vector(409.0519936203693, 78.58366137419546),
    with blueprint 'vehicle.audi.tt',
    with color Color(r=0.04513798494822896, g=0.9101142148435499, b=0.02208911337171382),
    with behavior NpcFollowLaneBehavior(12.708333333333334)


# the run ends once the ego has completed its lane change
terminate when lane_change_done(ego)
